name: ai-env
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - numpy=1.26.4
  - scipy=1.11.4
  - scikit-learn=1.2.2
  - pandas=2.1.1
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - ipywidgets=7.7.1

  - pip:
      - torch==2.5.1
      - torchvision==0.20.1
      - torchaudio==2.5.1
      - transformers==4.31.0
      - sentence-transformers==2.2.2
      - tokenizers==0.13.3
      - safetensors==0.3.1
      - huggingface-hub==0.17.3
      - regex==2023.6.3
      - requests==2.31.0
      - packaging==24.0
      - pyyaml==6.0
      - filelock==3.12.0
      - fsspec==2023.10.0
      - typing-extensions==4.8.0
      - langchain==0.3.27
      - langchain-community==0.3.27
      - langchain-core==0.3.74
      - langchain-ollama==0.3.7
      - langchain-text-splitters==0.3.9
      # optional for xlsx
      - openpyxl==3.1.2
      